REPLACE INTO provincia(id,nombre,abreviatura) VALUES (19,'Artemisa','AT');
REPLACE INTO provincia(id,nombre,abreviatura) VALUES (9,'Camaguey','CM');
REPLACE INTO provincia(id,nombre,abreviatura) VALUES (8,'Ciego de Ávila','CA');
REPLACE INTO provincia(id,nombre,abreviatura) VALUES (6,'Cienfuegos','CF');
REPLACE INTO provincia(id,nombre,abreviatura) VALUES (12,'Granma','GR');
REPLACE INTO provincia(id,nombre,abreviatura) VALUES (14,'Guantánamo','GU');
REPLACE INTO provincia(id,nombre,abreviatura) VALUES (11,'Holguín','HO');
REPLACE INTO provincia(id,nombre,abreviatura) VALUES (10,'Las Tunas','LT');
REPLACE INTO provincia(id,nombre,abreviatura) VALUES (4,'Matanzas','MT');
REPLACE INTO provincia(id,nombre,abreviatura) VALUES (20,'Mayabeque','MY');
REPLACE INTO provincia(id,nombre,abreviatura) VALUES (15,'Municipio Especial','IJ');
REPLACE INTO provincia(id,nombre,abreviatura) VALUES (3,'Pinar del Río','PR');
REPLACE INTO provincia(id,nombre,abreviatura) VALUES (7,'Sancti Spiritus','SS');
REPLACE INTO provincia(id,nombre,abreviatura) VALUES (13,'Santiago de Cuba','SC');
REPLACE INTO provincia(id,nombre,abreviatura) VALUES (5,'Villa Clara','VC');
REPLACE INTO provincia(id,nombre,abreviatura) VALUES (1,'La Habana','LH');