REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (1,'P1','LA ROSITA','PLAYA',2,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (2,'P2','ALBERRO','CVD JOSE MARTI, VEDADO',2,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (3,'P7','ALBERRO','PARQUE DE LA FRATERNIDAD',2,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (10,'P9','SANTA AMALIA','ISPJAE',17,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (11,'P10','VIBORA','NAUTICO',17,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (21,'A40','GUANABO','TERMINAL FFCC',14,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (22,'C5L','GUANABO','CASTILLA',14,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (23,'A62','GUANABO','VIRGEN DEL CAMINO',14,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (24,'A64','GUANABO','GUANABACOA',14,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (25,'A42','GUANABO','PEDRO PI - ALBERRO',14,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (26,'A42L','GUANABO','BAJURAYABO',14,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (27,'C3','GUANABO','SANTA BARBARA',14,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (28,'C5','GUANABO','JARUCO',14,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (239,'A45','GUANABO','GUANABACOA',14,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (283,'R23','LAWTON','GY 25, VEDADO',11,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (243,'R15','LAWTON','AVE PUERTO',11,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (244,'R88','LAWTON','FINCA EL ROCIO',11,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (245,'R54','LAWTON','PARQUE EL CURITA',11,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (67,'R1','LAWTON','FORTUNA',11,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (247,'R25','LAWTON','RPTO REBOREDO',11,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (248,'A18','LAWTON','EL VOLCAN',11,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (249,'A12','LAWTON','FORTUNA',11,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (250,'A4','LAWTON','CALABAZAR',11,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (253,'R174','LAWTON','LINEA Y F, VEDADO',11,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (254,'R37','LAWTON','MIRAMAR',11,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (255,'A11','LAWTON','EL ROBLE',11,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (295,'P12','SANTIAGO','PARQUE DE LA FRATERNIDAD',8,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (298,'P13','SANTIAGO','PARQUE DE LA FRATERNIDAD',8,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (300,'P16','SANTIAGO','HOSP AMEJEIRAS',8,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (301,'R88CF','LAWTON','PUENTE CALABAZAR',11,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (302,'P3','ALAMAR','PUENTE DE HIERRO',6,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (303,'P11','MICRO X','G Y 29, VEDADO',6,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (307,'P4','SAN AGUSTIN','TERMINAL FFCC',1,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (311,'P5','SAN AGUSTIN','TERMINAL FFCC',1,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (312,'P14','SAN AGUSTIN','PARQUE DE LA FRATERNIDAD',1,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (313,'P6','RPTO ELECTRICO','UNIVERSIDAD HABANA',10,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (314,'P8','RPTO ELECTRICO','VILLA PANAMERICANA',10,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (320,'A20','PALATINO','MIRAMAR',15,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (325,'A14','PALATINO','FONTANAR',15,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (326,'A14CF','PALATINO','SANTA CECILIA',15,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (329,'A32','PALATINO','RPTO CAMILO CIENFUEGOS',15,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (331,'A16','PALATINO','TERMINAL HAYFONG',15,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (348,'A26','RPTO GUITERAS','MICRO X',12,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (353,'A48','RPTO GUITERAS','PEÑALVER',12,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (356,'C7','RPTO GUITERAS','BRISAS DEL MAR',12,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (357,'A83','RPTO GUITERAS','FORTUNA',12,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (358,'A66','RPTO GUITERAS','EMBOQUE REGLA',12,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (360,'A60','RPTO GUITERAS','EMBOQUE REGLA',12,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (361,'A58','RPTO GUITERAS','TERMINAL OMNIBUS',12,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (362,'A65','RPTO GUITERAS','PALATINO',12,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (363,'C4','GUANABO','ENTRONQUE SAN GABRIEL',14,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (364,'A5','COTORRO','P. FRATERNIDAD',4,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (365,'A6','COTORRO','NAZARENO',4,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (366,'A7','COTORRO','VILLA PANAMERICANA',4,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (368,'A9','COTORRO','SANTIAGO VEGAS',4,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (369,'A10','COTORRO','LIGA CEGUERA',4,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (370,'A19','COTORRO','HOSP JULIO TRIGO',4,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (371,'A52','COTORRO','LA PALMA',4,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (372,'A21','COTORRO','TUNEL BAHIA',4,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (376,'C2','COTORRO','COMUNIDAD PRIMERO MAYO',4,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (377,'C1','COTORRO','COTORRO',4,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (378,'C1CF','COTORRO','TUNEL BAHIA',4,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (380,'A47','COTORRO','HOSP AMEIJEIRAS',4,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (381,'A6L','COTORRO','EL ALECRIN',4,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (382,'A24','GUANABACOA','LA CABAÑA',7,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (383,'A28','MICRO X','GUANABACOA',7,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (384,'A29','GUANABACOA','EMBOQUE REGLA',7,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (385,'A30','GUANABACOA','TNAL FFCC',7,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (386,'A31','GUANABACOA','EL ALECRIN - DAP',7,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (387,'A50','GUANABACOA','TNAL OMNIBUS',7,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (388,'A95','GUANABACOA','VEDADO',7,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (389,'C6','GUANABACOA','LA SEPULTURA',7,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (390,'A49','RPTO GUITERAS','TUNEL BAHIA',12,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (392,'A49CF','RPTO GUITERAS','PARQUE FRATERNIDAD',12,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (393,'A49L','RPTO GUITERAS','VIRGEN CAMINO',12,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (394,'A63','GUANABO','SANTA CRUZ DEL NORTE',14,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (395,'8','PLAYA','CUBA Y PEÑA POBRE',16,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (397,'69','PLAYA','LAWTON',16,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (398,'92','PLAYA','PUNTA BRAVA',16,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (399,'93','PLAYA','BARBOSA - JAIMANITAS',16,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (400,'179','PLAYA','VIRGEN DEL CAMINO',16,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (401,'191','PLAYA','SANTA FE',16,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (402,'192','PLAYA','GUATAO - PUNTA BRAVA',16,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (403,'193','PLAYA','ATABEY - JAIMANITAS',16,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (404,'420','PLAYA','BARACOA',16,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (409,'CB','RPTO CAMILO CIENFUEGOS','CUBA Y PEÑA POBRE',12,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (410,'A44','LISA','G Y 25, VEDADO',5,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (411,'34','LISA','TNAL FFCC',5,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (412,'36','LISA','PUNTA BRAVA - GUATAO',5,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (413,'40','LISA','SANTA FE',5,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (414,'43','BARBOSA','TNAL FFCC',5,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (415,'55','BARBOSA','HOSP AMEIJEIRAS',5,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (417,'113','BARBOSA','LAS GUASIMAS',5,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (418,'A70','LISA','VIRGEN CAMINO',5,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (419,'180','LISA','SANTA FE - PUNTA BRAVA',5,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (420,'222','LISA','P. FRATERNIDAD',5,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (421,'436','LISA','GUATAO - PUNTA BRAVA',5,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (422,'450A','LISA','FONTANAR',5,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (423,'486','LISA','UCI - PUNTA BRAVA',5,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (424,'487','LISA','LAS MARGARITAS',5,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (425,'490','LISA','UCI',5,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (429,'IP','FORTUNA','EXPOCUBA',13,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (431,'A1','LA ROSITA','VIRGEN DEL CAMINO',9,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (433,'A17','T.DIEZMERO','HOSP NAVAL',9,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (434,'A15','SANTIAGO VEGAS','MURGAS',3,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (435,'45','SANTIAGO VEGAS','LUTGARDITA',3,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (436,'46','SANTIAGO VEGAS','FINCA EL ROCIO',3,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (437,'160','SANTIAGO VEGAS','LA CEGUERA',3,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (438,'177','SANTIAGO VEGAS','CUJAE',3,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (439,'440','SANTIAGO VEGAS','AUTOPISTA MEDIODIA',3,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (440,'450','SANTIAGO VEGAS','MARIANAO',3,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (441,'450CF','SANTIAGO VEGAS','MARIANAO',3,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (442,'473','SANTIAGO VEGAS','HOSP NACIONAL',3,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (444,'488','SANTIAGO VEGAS','HOSP JULIO TRIGO',3,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (446,'CXXN','SANTIAGO VEGAS','TERMINAL 5',3,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (449,'A97','PLAYA','HUSILLO',16,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (451,'A35','T.DIEZMERO','CUJAE',9,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (452,'A2','LA ROSITA','TNAL FFCC',9,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (453,'A3','T.DIEZMERO','HOSP MILITAR',9,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (455,'PC','SAN AGUSTIN','RPTO C.CIENFUEGOS',1,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (456,'A33','LISA','HOSP JOAQUIN ALBARRAN',5,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (457,'34L','LISA','MIRAMAR',5,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (458,'A27','PALATINO','MUELLE LUZ',15,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (459,'A51','PALATINO','SANTA FE',15,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (460,'A81','PALATINO','SANTA CECILIA',15,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (461,'P15','SANTA FE','G Y 25',7,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (462,'A68','RPTO GUITERAS','PALATINO',12,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (463,'A13','FORTUNA','P.FRATERNIDAD',13,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (464,'A87','FORTUNA','TNAL OMNIBUS',13,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (465,'A67','RPTO GUITERAS','PALATINO',12,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (466,'476','SANTIAGO VEGAS','LA CEIBA',3,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (490,'A56','RPTO GUITERAS','CARCEL Y PEÑA POBRE',12,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (488,'A71','RPTO GUITERAS','12 Y 23 VEDADO',12,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (489,'A72','REGLA','RPTO C. CIENFUEGOS',12,1);
REPLACE INTO ruta(id,nombre,origen,destino,terminal_id,provincia_id) VALUES (467,'A91','PLAYA','SAN AGUSTIN',16,1);